Develop pokedex
dafnemus/pokedex pull request #1
Opened 2021-08-02 14:59 UTC by dafnemus

# Versión actual:

![avance](https://user-images.githubusercontent.com/57498199/127881813-58dae56c-3cf0-4e51-b168-7817026415d4.gif)

## lo que falta: Hacer que llegue el pokemon al modal
![Captura de pantalla de 2021-08-02 11-56-37](https://user-images.githubusercontent.com/57498199/127881896-ba6c9cc3-5618-4cfa-928c-73831c197a18.png)

2021-08-03 13:59 UTC, briangerez requested changes
Gran trabajo Dafne!! Me gusta mucho como va quedando la pokedex 🎉 Avanzaste mucho en comparación con otros prs! 

Algunos comentarios sutiles y algunos que deberíamos empezar a tomar como hábitos para que el futuros proyectos nos ocurran lo menos posible (por ejemplo, cómo llamamos a las variables, estructura de carpetas, los colores como variables, uso de algunos hooks).

Bien haciendo el PR con esta funcionalidad y dejando para otro lo del modal!

A meterle a estas correcciones y a seguir avanzando para el siguiente ejercicio!!

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +function App() {
Por lo general, se deja este archivo para que se puedan hacer configuraciones globales, como por ejemplo el routing, contexto globales, notificaciones, étc. 

Para este caso en particular solemos tener una carpeta llamada `screen` donde se colocan las screens importantes con sus respectivos componentes y sub-screens dentro. 

Lo que hiciste no esta para nada mal ya que no era necesario realizarlo así, pero para que lo sepas y en lo que viene poder estructurar las carpetas de manera diferente! 🚀

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +  const [pokemon, setPokemon] = useState({ info: [], isOpen: false });
Veo que para el modal y para la información del pokemon utilizas un mismo state. Quizás, para este caso podrías hacerlo en states separados para que uno sea del modal y otro del pokemon

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +  const getPokemon = async (pokemon) => {
Tanto la función de getPokemon como el buscador de pokemones (podríamos ponerle `getPokemonList` ) podrían estar ubicados en una carpeta llamada `services` y por cada "modelo de datos" poner un archivo llamado pokemon.js. Allí estarían los distintos servicios y luego en la screen sólo los llamarías a las funciones, pero todo lo que tenga que ver con la configuración de la API podría abstraerse allí. 
Igualmente, con Agus le podemos explicar un poco cómo estructuramos las carpetas y el uso de los servicios

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +  const search = (busquedaPokemon) => {
Podríamos cambiar el nombre de esta función a pokemonFilter y el parámetro ponerlo en inglés para que tenga más lógica con toda la app 😄 

```suggestion
  const pokemonFilter = (pokemon) => {
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +  };
Podrías hacer directamente:

```suggestion
  const sortAlphabet = () => setStateFilter(!stateFilter);
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +    <div className={styles.mainContain}>
```suggestion
    <div className={styles.mainContainer}>
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +      <div className={styles.containHeader}>
```suggestion
      <div className={styles.containerHeader}>
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/index.js
> +function BigCardPokemon({
Quizás con colocar `BigCard` el componente queda más genérico :D

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/App.js
> +    <div className={styles.mainContain}>
Veo que en varios lugares pusiste contain, debería ser container :D

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/index.js
> +        <div>
A veces, no es necesario utilizar `div` para hacer agrupaciones de elementos. Quizás, para estos casos, es mejor utilizar un Fragment ya que no genera gran esfuerzo para renderizarlo en el DOM. 

El fragment se escribe: <> </>

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/index.js
> +            <p>{weigth}</p>
Para estos casos podrías utilizar span en vez de p 
y :P
```suggestion
            <p>{weight}</p>
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/index.js
> +            <img src={iconRuler} alt='ruler' />
```suggestion
            <img src={iconRuler} alt='Ruler icon' />
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/index.js
> +            <p>Wheight</p>
```suggestion
            <p>Weight</p>
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/index.js
> +BigCardPokemon.propTypes = {
Bien ahi esos propTypes!!!

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/styles.module.scss
> +  background-color: black;
Importaría los colores y usaría la variable:

```suggestion
  background-color: $black;
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/styles.module.scss
> +  z-index: 2;
Creo que lo había comentado en otro PR anterior, por lo general tratamos de ordenar alfabéticamente las props de css. Pero tranqui, para ahora no te lo vamos a pedir pero para que lo tengan en cuenta a futuro.

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/styles.module.scss
> +  color: white;
```suggestion
  color: $white;
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/styles.module.scss
> +  color: white;
```suggestion
  color: $white;
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/bigCard/styles.module.scss
> +  background-color: transparent;
```suggestion
  background-color: $transparent;
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/containMinCards/index.js
> +  value
Este ordenamiento podrías colocarlo dentro de un useEffect ;)

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/containMinCards/index.js
> +      {pokemons.map((poke) => {
```suggestion
      {pokemons.map((pokemon) => {
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/containMinCards/styles.module.scss
> +@import '../../static/colors/colors.module.scss';
Se importa pero no se utilizan colores aquí

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/cuadrilla/index.js
> +  console.log(poke);
remover console.log

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/cuadrilla/index.js
> +        <div onClick={openModal} className={styles[poke.types[0].type.name]}>
Buenaa el uso de styles acá

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/cuadrilla/styles.module.scss
> +.grass {
colocar una línea en blanco entre cada clase

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/cuadrilla/styles.module.scss
> +.psychic .namePokemon {
Tener cuidado cómo estamos utilizando los nombres en inglés. 

Si ponemos pokemonName, significa "nombre de pokemon"
Si ponemos namePokemon, significa "pokemon de nombre"

```suggestion
.psychic .pokemonName {
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/components/filter/index.js
> +      )}
Puedes usar String Interpolation para hacerlo mas legible 

```suggestion
        <a className={styles.filter}>{`${value ? 'A-Z' : '#'}`}</a>
```

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/context/index.js
> +/*
Eliminar archivo si no es utilizado

2021-08-03 13:59 UTC, briangerez commented on pokedex/src/static/colors/colors.module.scss
> +$rock: #b69e31;
Geniaal!

2021-08-04 16:59 UTC, dafnemus commented on pokedex/src/components/App.js
> +function App() {
Okiiii :), para la próxima.

2021-08-04 17:00 UTC, dafnemus commented on pokedex/src/components/App.js
> +  const [pokemon, setPokemon] = useState({ info: [], isOpen: false });
Modificado... pase el isOpen a otro componente al final.

2021-08-04 17:01 UTC, dafnemus commented on pokedex/src/components/App.js
> +  const getPokemon = async (pokemon) => {
okii

2021-08-04 17:02 UTC, dafnemus commented on pokedex/src/components/App.js
> +  const search = (busquedaPokemon) => {
listo

2021-08-04 17:02 UTC, dafnemus commented on pokedex/src/components/App.js
> +  };
Tomo la segerencia

2021-08-04 17:02 UTC, dafnemus commented on pokedex/src/components/App.js
> +    <div className={styles.mainContain}>
Actualizado

2021-08-04 17:03 UTC, dafnemus commented on pokedex/src/components/App.js
> +      <div className={styles.containHeader}>
Actualizado

2021-08-04 17:03 UTC, dafnemus commented on pokedex/src/components/bigCard/index.js
> +function BigCardPokemon({
Genial, listoo

2021-08-04 17:04 UTC, dafnemus commented on pokedex/src/components/bigCard/index.js
> +        <div>
Si lo conozco, solo que use div pq sabía que lo iba a a usar para clases mas tarde.

2021-08-04 17:09 UTC, dafnemus commented on pokedex/src/context/index.js
> +/*
Listo

2021-08-04 17:09 UTC, dafnemus commented on pokedex/src/components/filter/index.js
> +      )}
Actualizado

2021-08-04 17:09 UTC, dafnemus commented on pokedex/src/components/cuadrilla/styles.module.scss
> +.psychic .namePokemon {
cambiado

2021-08-04 17:10 UTC, dafnemus commented on pokedex/src/components/cuadrilla/styles.module.scss
> +.grass {
listo

2021-08-04 17:14 UTC, dafnemus commented on pokedex/src/components/cuadrilla/index.js
> +  console.log(poke);
Removido

2021-08-04 17:14 UTC, dafnemus commented on pokedex/src/components/containMinCards/styles.module.scss
> +@import '../../static/colors/colors.module.scss';
Eliminado

2021-08-04 17:15 UTC, dafnemus commented on pokedex/src/components/containMinCards/index.js
> +      {pokemons.map((poke) => {
listo

2021-08-04 17:15 UTC, dafnemus commented on pokedex/src/components/bigCard/styles.module.scss
> +  z-index: 2;
Ya las ordene

2021-08-04 17:16 UTC, dafnemus commented on pokedex/src/components/bigCard/styles.module.scss
> +  color: white;
listo

2021-08-04 17:16 UTC, dafnemus commented on pokedex/src/components/bigCard/styles.module.scss
> +  color: white;
listo

2021-08-04 17:16 UTC, dafnemus commented on pokedex/src/components/bigCard/styles.module.scss
> +  background-color: black;
listo

2021-08-04 17:17 UTC, dafnemus commented on pokedex/src/components/bigCard/index.js
> +            <p>Wheight</p>
listo

2021-08-04 17:18 UTC, dafnemus commented on pokedex/src/components/bigCard/index.js
> +            <img src={iconRuler} alt='ruler' />
listo

2021-08-04 17:19 UTC, dafnemus commented
#  Versión actual:
## mobile:
![mobilepokedex](https://user-images.githubusercontent.com/57498199/128225532-fe92cc13-8000-4aeb-ab83-3f91ef089453.gif)

## desktop:
![apppokedex](https://user-images.githubusercontent.com/57498199/128225596-2629e548-6294-46d6-b05d-6eba82640865.gif)

2021-08-25 17:40 UTC, merged